spring:
  application:
    name: elior
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_elior
    username: elior
    password: elior
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8080
