spring:
  application:
    name: elior
  datasource:
    url: jdbc:mysql://localhost:3306/elior_db
    username: elior
    password: elior
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8080
