spring:
  application:
    name: elior
  datasource:
    url: jdbc:postgresql://localhost:5432/db_elior
    username: elior
    password: elior
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8080
